// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fowdzmkxmvocegczvbua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvd2R6bWt4bXZvY2VnY3p2YnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjM2NDUsImV4cCI6MjA1OTM5OTY0NX0.6M9L_2MCO1PES2FWM7n5bddbB6H0CpHp-gpcoqK_Omw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);